repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --line-length=120
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=120"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--line-length=120", "--profile=black"]